import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  containerSafeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
    paddingHorizontal: 10,
    backgroundColor: 'white',
  },
  hiddenTextInput: {
    // borderColor: '#004D40',
    // borderWidth: 2,
    // borderRadius: 5,
    // padding: 12,
    // marginTop: 15,
    // width: 300,
    // color: 'white',
    position: 'absolute',
    width: 1,
    height: 1,
    opacity: 0,
  },
  wrapperTypeMessure: {
    flexDirection: 'row',
    padding: 5,
    justifyContent: 'center',
    width: '60%',
    alignItems: 'center',
    backgroundColor: Colors.gray.gray95,
    borderRadius: 30,
  },
  wrapperDataItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingVertical: 10,
    alignItems: 'center',
    // backgroundColor: 'red',
    // marginVertical: 10,
  },
  inputCholesterol: {
    position: 'absolute',
    width: '100%',
    backgroundColor: 'green',
    borderRadius: 20,
    opacity: 0,
  },
  wrapperInputCholesterol: {
    width: widthDevice / 2.8,
    borderRadius: 25,
    paddingVertical: 8,
    flexDirection: 'row',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.blue.blue95,
  },
  wrapperRowItem: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  otpInputText: {
    fontSize: 32,
    textAlign: 'center',
    alignSelf: 'center',
    justifyContent: 'center',
    color: Colors.blue.blue30,
    fontWeight: 'bold',
    paddingVertical: 0,
    // paddingHorizontal: 5,
    // width: 20,
    // backgroundColor: 'red',
  },
  completeButton: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    width: '90%',
    backgroundColor: Colors.gray.gray10,
    paddingVertical: 13,
    borderRadius: 20,
    alignItems: 'center',
  },
  otpInputView: {
    // borderColor: 'gray',
    // minWidth: '13%',
    // borderWidth: 0.5,
    justifyContent: 'center',
    // backgroundColor: 'white',
    // borderRadius: 5,
    marginHorizontal: 2,
    // width: 20,
    height: 55,
  },
  invalidWrapper: {
    backgroundColor: Colors.pink.pink80,
  },
  inputContainerPressable: {
    width: '90%',
    // marginBottom: 5,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 2,
    // flex: 1,
    // backgroundColor: 'red',
  },
  activeInputText: {
    color: Colors.red.red60,
  },
  inputSection: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    flex: 1,
  },
  wrapperInputHeath: {
    width: 100,
    height: 110,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: Colors.gray.gray95,
  },
  containerBloodSugar: {
    paddingVertical: 10,
    flex: 1,
    // justifyContent: 'space-between',
    // flexDirection: 'row',
    // backgroundColor: 'red',
    paddingHorizontal: 10,
  },
  wrapperClose: {
    height: 30,
    width: 30,
    borderRadius: 30,
    backgroundColor: Colors.gray.gray10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textTitle: {
    flex: 1,
    textAlign: 'center',
    alignSelf: 'center',
    color: Colors.gray.gray10,
    marginLeft: 20,
    fontSize: 19,
  },
  containerInputHealth: {
    paddingVertical: 20,
    // flex: 1,
    justifyContent: 'space-between',
    flexDirection: 'row',
    // backgroundColor: 'red',
    paddingHorizontal: 10,
    marginTop: 40,
  },
  wrapperActiveInputHealth: {
    backgroundColor: Colors.blue.blue80,
  },
  wrapperTitle: {paddingVertical: 10, flexDirection: 'row'},
  placeholderInput: {
    width: 20,
    paddingHorizontal: 2,
    backgroundColor: Colors.blue.blue50,
    height: 5,
  },
  textLabelInput: {textAlign: 'center', color: Colors.blue.blue30},
  messureButton: {
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    paddingHorizontal: 10,
    width: '50%',
  },
  wrapperDatePicker: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingVertical: 10,
    justifyContent: 'center',
    width: '70%',
    alignItems: 'center',
    backgroundColor: Colors.blue.blue80,
    borderRadius: 20,
  },
  textToday: {
    marginLeft: 5,
    fontWeight: 'bold',
    color: Colors.gray.gray20,
  },
  wrapperTime: {
    paddingHorizontal: 15,
    height: 30,
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: Colors.gray.gray30,
    alignItems: 'center',
    borderRadius: 20,
  },
});

export default styles;
