// export const isStatusDeleteAccount = state => state.user.statusDeleteAccount;
// export const statusConfirmOtpDelete = state => state.user.statusConfirmDelete;
// export const getErrorMessageConfirm = state => state.user.errorDeleteAccount;
export const statusUpdateUserSelector = state => state.user.statusUpdateUser;
export const errorUpdateUserSelector = state => state.user.errorUpdateUser;
export const updatedUserSelector = state => state.user.updatedUser;
export const statusRegisterSelector = state => state.user.statusRegisterUser;
export const messageRegisterSelector = state => state.user.messageRegisterUser;
// export const getStatusSetLanguage = state => state.user.statusSetLanguage;
// export const getCurrentLanguage = state => state.user.currentUserLanguage;
