import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  avatarIcon: {
    height: 45,
    width: 45,
    borderRadius: 20,
    backgroundColor: 'lightgray',
  },
  wrapperFixedHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'white',
    height: 70,
    paddingHorizontal: 15,
    width: widthDevice,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  fontSize24: {fontSize: 20},
  wrapperHeader: {
    height: heightDevice * 0.4,
    backgroundColor: '#2544BD',
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageBackground: {
    width: widthDevice * (180 / 390),
    height: heightDevice * (190 / 800),
  },
  wrapperTitle: {
    paddingRight: 12,
    flex: 1,
    // backgroundColor: 'red',
    height: '80%',
  },
  wrapperBellIcon: {
    backgroundColor: 'white',
    borderRadius: 30,
    padding: 8,
    alignSelf: 'flex-end',
    marginBottom: 20,
  },
  greetingText: {textAlign: 'right', color: Colors.whiteColor},
  titleText: {
    textAlign: 'right',
    fontSize: 22,
    color: Colors.whiteColor,
    fontWeight: '700',
    lineHeight: 33,
  },
  doctorContainer: {marginHorizontal: 15, paddingTop: 10},
  doctorName: {
    fontWeight: 'bold',
    fontSize: 16,
    paddingVertical: 5,
  },
  containerAsking: {
    flexDirection: 'row',
    borderRadius: 16,
    backgroundColor: Colors.primary,
    paddingTop: 10,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  textBold: {fontWeight: 'bold'},
  buttonAsking: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    backgroundColor: '#FFE699',
    borderRadius: 8,
    alignSelf: 'center',
  },
  titleAsking: {
    textAlign: 'center',
    paddingVertical: 10,
    marginTop: 10,
  },
  wrapperTitleAsking: {
    flex: 1,
    paddingHorizontal: 10,
  },
  imageDoctorAsking: {height: 120, width: 70, marginHorizontal: 10},
  paddingH10: {paddingHorizontal: 10},
  imageDoctor: {height: 70, width: 70, borderRadius: 10},
  wrapperMainDoctor: {
    flexDirection: 'row',
    borderBottomColor: Colors.whiteColor,
    borderBottomWidth: 1,
    borderStyle: 'solid',
    paddingBottom: 10,
  },
  wrapperDoctorInfo: {
    padding: 15,
    marginVertical: 10,
    backgroundColor: Colors.primary,
    borderRadius: 16,
  },
  wrapperCardItem: {
    width: widthDevice - 30,
    alignSelf: 'center',
    elevation: 1,
    backgroundColor: 'white',
    borderRadius: 16,
    paddingHorizontal: 15,
    marginBottom: 10,
    paddingVertical: 10,
  },
  wrapperOptionIcon: {
    padding: 10,
    borderRadius: 20,
    backgroundColor: '#E1E9FF',
    alignSelf: 'center',
  },
  wrapperHeaderList: {
    paddingHorizontal: 15,
    paddingBottom: 10,
    paddingTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wrapperContentCard: {
    paddingVertical: 10,
    borderBottomColor: Colors.gray.gray90,
    borderBottomWidth: 1,
  },
  wrapperNameLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 5,
    alignItems: 'center',
  },
  statusText: {
    color: 'white',
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 12,
    minWidth: 80,
    alignItems: 'center',
    borderRadius: 8,
    fontWeight: '600',
    // backgroundColor: '#07C558',
    textAlign: 'center',
  },
  statusDangerText: {
    color: 'white',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: '600',
    backgroundColor: '#FF5449',
    textAlign: 'center',
  },
  timeText: {color: '#898989'},
  wrapperValue: {
    paddingVertical: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  navigationText: {
    color: '#1A54DB',
    fontWeight: 'bold',
    paddingVertical: 10,
    paddingHorizontal: 5,
    // backgroundColor: 'red',
    fontSize: 12,
  },
  typeTimeText: {fontWeight: 'bold', paddingHorizontal: 5},
  wrapperTypeTime: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 3,
  },
  unitText: {
    fontSize: 14,
    fontWeight: '600',
    alignSelf: 'flex-end',
    marginBottom: 3,
    marginLeft: 2,
  },
  wrapperSubvalue: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    alignItems: 'center',
  },
  wrapperListCard: {
    backgroundColor: Colors.backgroundColor,
    borderTopRightRadius: 32,
    borderTopLeftRadius: 32,
    marginTop: 0,
  },
});

export default styles;
