import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet, Platform} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  borderAvatar: {
    borderColor: Colors.primary,
    borderWidth: 2,
    borderRadius: 40,
    borderStyle: 'solid',
  },
  avatarIcon: {
    height: 45,
    width: 45,
    borderRadius: 20,
    // backgroundColor: Colors.gray.gray90,
    // backgroundColor: 'lightgray',
  },
  wrapperFixedHeader: {
    height: heightDevice * 0.25,
    paddingHorizontal: 15,
    width: widthDevice,
  },
  messageSection: {
    flexDirection: 'row',
    paddingHorizontal: 10,
    width: 80,
    justifyContent: 'flex-start',
    // backgroundColor: 'red',
  },
  imageEmpty: {
    width: 135,
    height: 135,
  },
  containerModalNotify: {
    // paddingTop: 20,
    backgroundColor: Colors.backgroundColor,
    width: widthDevice - 24,
    borderRadius: 10,
    height: heightDevice * 0.69,
    paddingBottom: 20,
  },
  headerModal: {
    height: 50,
    width: widthDevice * 0.8,
    // backgroundColor: '#255D54',
    backgroundColor: 'white',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    paddingLeft: 10,
  },
  modalBody: {
    width: widthDevice * 0.8,
    height: heightDevice * 0.45,
    backgroundColor: Colors.backgroundColor,
    borderBottomLeftRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textModal: {
    textAlign: 'center',
    marginBottom: 10,
    marginTop: 12,
    color: 'gray',
  },
  container: {
    flex: 1,
    backgroundColor: Colors.backgroundColor,
  },
  fontSize24: {fontSize: 20},
  wrapperHeader: {
    height: heightDevice * 0.4,
    backgroundColor: '#2544BD',
    flexDirection: 'row',
    alignItems: 'center',
  },
  imageBackground: {
    width: widthDevice * (180 / 390),
    height: heightDevice * (190 / 800),
  },
  wrapperTitle: {
    paddingRight: 12,
    flex: 1,
    // backgroundColor: 'red',
    height: '80%',
  },
  wrapperBellIcon: {
    backgroundColor: 'white',
    borderRadius: 30,
    padding: 8,
    alignSelf: 'flex-end',
    marginBottom: 20,
  },
  greetingText: {textAlign: 'right', color: Colors.whiteColor},
  titleText: {
    textAlign: 'right',
    fontSize: 22,
    color: Colors.whiteColor,
    fontWeight: '700',
    lineHeight: 33,
  },
  doctorContainer: {
    marginHorizontal: 15,
    height: heightDevice * 0.22,
    marginBottom: 10,
    marginTop: -(heightDevice * 0.22) / 1.5,
  },
  wrapperDoctorInfo: {
    padding: 16,
    backgroundColor: Colors.primary,
    marginTop: 10,
    justifyContent: 'center',
    borderRadius: 16,
    height: heightDevice * 0.19,
  },
  doctorName: {
    fontWeight: 'bold',
    fontSize: 16,
  },
  containerAsking: {
    flexDirection: 'row',
    borderRadius: 16,
    backgroundColor: Colors.primary,
    paddingTop: 10,
    marginVertical: 10,
    paddingHorizontal: 10,
  },
  textBold: {fontWeight: 'bold'},
  buttonAsking: {
    paddingHorizontal: 15,
    paddingVertical: 7,
    backgroundColor: '#FFE699',
    borderRadius: 8,
    alignSelf: 'center',
  },
  titleAsking: {
    textAlign: 'center',
    paddingVertical: 10,
    marginTop: 10,
  },
  wrapperTitleAsking: {
    flex: 1,
    paddingHorizontal: 10,
  },
  imageDoctorAsking: {height: 120, width: 70, marginHorizontal: 10},
  wrapperInfoText: {
    paddingHorizontal: 12,
    // alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 5,
  },
  imageDoctor: {borderRadius: 10},
  wrapperMainDoctor: {
    flexDirection: 'row',
    // paddingVertical: 10,
  },

  wrapperCardItem: {
    width: widthDevice - 30,
    alignSelf: 'center',
    elevation: 1,
    backgroundColor: 'white',
    borderRadius: 16,
    paddingHorizontal: 15,
    marginBottom: 10,
    ...Platform.select({
      android: {
        elevation: 2,
      },
      ios: {
        shadowColor: '#a8bed2',
        shadowOpacity: 1,
        shadowRadius: 6,
        shadowOffset: {
          width: 2,
          height: 2,
        },
      },
    }),
    paddingVertical: 5,
  },
  wrapperOptionIcon: {
    padding: 10,
    borderRadius: 20,
    backgroundColor: '#E1E9FF',
    alignSelf: 'center',
  },
  wrapperHeaderList: {
    paddingHorizontal: 15,
    paddingBottom: 10,
    paddingTop: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  wrapperContentCard: {
    paddingVertical: 10,
    borderBottomColor: Colors.gray.gray95,
    borderBottomWidth: 1,
  },
  wrapperNameLine: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingBottom: 5,
    alignItems: 'center',
  },
  statusText: {
    color: 'white',
    paddingHorizontal: 8,
    paddingVertical: 5,
    fontSize: 12,
    minWidth: 80,
    alignItems: 'center',
    borderRadius: 8,
    fontWeight: '600',
    // backgroundColor: '#07C558',
    textAlign: 'center',
  },
  statusDangerText: {
    color: 'white',
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    fontSize: 12,
    fontWeight: '600',
    backgroundColor: '#FF5449',
    textAlign: 'center',
  },
  timeText: {color: '#898989'},
  wrapperValue: {
    paddingVertical: 10,
    justifyContent: 'space-between',
    alignItems: 'center',
    flexDirection: 'row',
  },
  navigationText: {
    color: '#1A54DB',
    fontWeight: 'bold',
    paddingVertical: 10,
    paddingLeft: 15,
    // backgroundColor: 'red',
    fontSize: 12,
  },
  typeTimeText: {fontWeight: 'bold', paddingHorizontal: 5},
  wrapperTypeTime: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 3,
  },
  unitText: {
    fontSize: 14,
    fontWeight: '600',
    alignSelf: 'flex-end',
    marginBottom: 3,
    marginLeft: 2,
  },
  wrapperSubvalue: {
    flexDirection: 'row',
    paddingHorizontal: 15,
    alignItems: 'center',
  },
});

export default styles;
