import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  containerSafeArea: {
    flex: 1,
    backgroundColor: Colors.whiteColor,
  },
  wrapperTitle: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: widthDevice,
    paddingTop: 10,
    // backgroundColor: Colors.blue.blue90,
    height: 100,
  },
  removeModal: {
    backgroundColor: 'transparent',
    position: 'absolute',
    top: -heightDevice / 2 + 30,
    right: -widthDevice / 2 + 15,
    padding: 10,
    width: widthDevice / 2 + 50,
    shadowColor: '#000',
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 1,
  },
  wrapperIconSection: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 5,
  },
  iconPlus: {margin: 10},
  iconClock: {marginLeft: 10, marginRight: 5},
  imageDoctor: {
    width: 75,
    height: 75,
    borderRadius: 4,
  },
  wrapperDoctorItem: {
    padding: 10,
    backgroundColor: Colors.whiteColor,
    borderRadius: 10,
    marginVertical: 10,
    marginHorizontal: 1,
    elevation: 1,
  },
  wrapperProfileDoctor: {
    flexDirection: 'row',
    // borderBottomColor: Colors.gray.gray80,
    // borderBottomWidth: 1.5,
    paddingVertical: 5,
    // marginBottom: 5,
    // borderStyle: 'dashed',
  },
  wrapperLabel: {
    position: 'absolute',
    top: -10,
    right: -10,
    paddingHorizontal: 10,
    flexDirection: 'row',
    borderTopRightRadius: 10,
    paddingVertical: 2,
    alignItems: 'center',
    borderBottomLeftRadius: 10,
    backgroundColor: Colors.blue.blue40,
  },
  optionButton: {
    borderRadius: 15,
    alignItems: 'center',
    padding: 10,
    backgroundColor: 'white',
    marginTop: 10,
  },
  wrapperProfileContent: {paddingHorizontal: 10},
  textDoctorName: {marginBottom: 5},
  textDoctorDepartment: {
    marginBottom: 5,
    color: Colors.red.red50,
    paddingVertical: 5,
    backgroundColor: Colors.red.red90,
    paddingHorizontal: 15,
    borderRadius: 20,
  },
  wrapperMydoctor: {
    backgroundColor: 'white',
    marginTop: -40,
    width: widthDevice,
    elevation: 0,
    paddingHorizontal: 10,
    paddingVertical: 20,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    zIndex: 100,
    alignSelf: 'center',
  },
  container: {flex: 1, backgroundColor: Colors.whiteColor},
  // wrapperAddressDoctor: {flexDirection: 'row', alignItems: 'center'},
});

export default styles;
