import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  containerSafeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  wrapperHeaderTitle: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    backgroundColor: 'white',
  },
  phoneIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
    borderRadius: 20,
    padding: 5,
    backgroundColor: Colors.blue.blue30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  wrapperDepartmentLabel: {
    height: 20,
    width: 120,
    paddingHorizontal: 10,
    backgroundColor: Colors.red.red80,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  textHeader: {color: Colors.blue.blue30, paddingLeft: 5, marginBottom: 5},
  scrollContainer: {flex: 1, backgroundColor: 'white'},
  imageDoctor: {
    width: widthDevice,
    height: (widthDevice * 5) / 8,
    backgroundColor: 'white',
  },
  wrapperImageDoctor: {
    width: widthDevice,
    height: (widthDevice * 5) / 8 + 60,
    backgroundColor: Colors.backgroundColor,
    // backgroundColor: 'red',
  },
  wrapperCardPackage: {
    backgroundColor: Colors.blue.blue90,
    padding: 10,
    borderRadius: 20,
    marginTop: 10,
  },
  decoration: {
    position: 'absolute',
    top: 20,
    backgroundColor: Colors.blue.blue80,
    borderRadius: 50,
    right: -40,
    height: 100,
    width: 100,
  },
  wrapperAnimationHeader: {
    position: 'absolute',
    top: 0,
    zIndex: 100,
    elevation: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  wrapperFooterCard: {
    paddingVertical: 5,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 2,
    borderTopColor: 'white',
  },
  buyPackageButton: {
    paddingHorizontal: 20,
    paddingVertical: 5,
    marginTop: 5,
    backgroundColor: Colors.blue.blue50,
    borderRadius: 20,
  },
  inforCard: {paddingVertical: 10},
  wrapeprCardInfo: {
    paddingBottom: 5,
    backgroundColor: 'white',
    // elevation: 4,
    width: '100%',
    position: 'absolute',
    borderRadius: 20,
    paddingHorizontal: 20,
    alignSelf: 'center',
    top: -90,
  },
  closeIcon: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'white',
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 10,
    zIndex: 999,
  },
  wrapperDoctorInfo: {
    paddingHorizontal: 10,
    // backgroundColor: 'green',
  },
  textDoctorName: {marginBottom: 5},
  textDoctorDepartment: {
    color: Colors.textGrayColor,
  },
  wrapperAddress: {
    paddingVertical: 10,
    flexDirection: 'row',
  },
  toggleIcon: {
    position: 'absolute',
    padding: 5,
    borderRadius: 15,
    // borderWidth: 1,
    // backgroundColor: 'red',
    bottom: 0,
    right: 0,
  },
  wrapperDescription: {
    paddingVertical: 10,
    borderTopColor: 'lightgray',
    // backgroundColor: 'red',
    borderTopWidth: 1,
    borderStyle: 'solid',
  },
  wrapperDoctorContainer: {
    padding: 10,
    flexDirection: 'row',
    backgroundColor: Colors.gray.gray95,
    borderRadius: 10,
  },
});

export default styles;
