import {heightDevice, widthDevice} from 'assets/constans';
import {StyleSheet} from 'react-native';
import Colors from 'theme/Colors';

const styles = StyleSheet.create({
  containerSafeArea: {
    flex: 1,
  },
  container: {
    flex: 1,
  },
  wrapperHeaderTitle: {
    paddingHorizontal: 10,
    paddingVertical: 15,
    backgroundColor: 'white',
  },
  phoneIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
    borderRadius: 20,
    padding: 5,
    backgroundColor: Colors.blue.blue30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  removeModal: {
    backgroundColor: 'white',
    position: 'absolute',
    top: -heightDevice / 2 + 50,
    right: -widthDevice / 2 + 15,
    padding: 10,
    width: widthDevice / 2 + 50,
    shadowColor: '#000',
    borderRadius: 10,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 1,
  },
  removeButton: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
    width: widthDevice / 3,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.blue.blue40,
  },
  cancelRemoveButton: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 20,
    width: widthDevice / 3,
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    borderColor: Colors.gray.gray80,
  },
  wrapperHeaderFlatlis: {
    paddingVertical: 15,
    paddingHorizontal: 5,
    borderRadius: 20,
  },
  wrapperRemoveAction: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: widthDevice - 80,
    paddingVertical: 5,
    paddingTop: 10,
  },
  confirmRemoveModal: {
    backgroundColor: 'whitesmoke',
    width: widthDevice - 24,
    alignItems: 'center',
    paddingVertical: 15,
    paddingHorizontal: 20,
    justifyContent: 'center',
    // height: heightDevice / 4,
    borderRadius: 20,
  },
  moreIcon: {
    position: 'absolute',
    top: 10,
    right: 10,
    borderRadius: 20,
    padding: 10,
    zIndex: 100,
    backgroundColor: 'white',
  },
  wrapperDepartmentLabel: {
    height: 20,
    width: 120,
    paddingHorizontal: 10,
    backgroundColor: Colors.red.red80,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 5,
  },
  textHeader: {color: Colors.blue.blue30, paddingLeft: 5, marginBottom: 5},
  scrollContainer: {flex: 1, backgroundColor: 'white'},
  imageDoctor: {
    width: widthDevice,
    height: (widthDevice * 5) / 6,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
  },
  wrapeprCardInfo: {
    paddingBottom: 5,
    backgroundColor: 'white',
    // elevation: 4,
    width: '90%',
    position: 'absolute',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    paddingHorizontal: 20,
    alignSelf: 'center',
    top: (widthDevice * 5) / 6 - 90,
  },
  wrapperCardPackage: {
    backgroundColor: Colors.blue.blue90,
    padding: 10,
    borderRadius: 20,
    marginTop: 10,
  },
  decoration: {
    position: 'absolute',
    top: 20,
    backgroundColor: Colors.blue.blue80,
    borderRadius: 50,
    right: -40,
    height: 100,
    width: 100,
  },
  decorationActived: {
    position: 'absolute',
    top: 0,
    backgroundColor: Colors.pink.pink80,
    borderRadius: 40,
    right: 30,
    padding: 40,
  },
  wrapperAnimationHeader: {
    position: 'absolute',
    top: 0,
    zIndex: 100,
    elevation: 1,
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  wrapperActivePackage: {
    backgroundColor: Colors.pink.pink90,
    padding: 10,
    borderRadius: 20,
    zIndex: 100,
    marginTop: 10,
  },

  wrapperFooterCard: {
    paddingVertical: 5,
    paddingHorizontal: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderTopWidth: 2,
    borderTopColor: 'white',
  },
  buyPackageButton: {
    paddingHorizontal: 30,
    paddingVertical: 5,
    marginTop: 5,
    backgroundColor: Colors.blue.blue30,
    borderRadius: 20,
  },
  inforCard: {paddingVertical: 10},

  closeIcon: {
    position: 'absolute',
    top: 10,
    left: 10,
    backgroundColor: 'white',
    padding: 10,
    borderRadius: 20,
    zIndex: 999,
  },
  wrapperDoctorInfo: {
    paddingHorizontal: 10,
    // backgroundColor: 'green',
  },
  textDoctorName: {marginBottom: 5},
  textDoctorDepartment: {
    color: Colors.textGrayColor,
  },
  wrapperAddress: {
    paddingVertical: 10,
    flexDirection: 'row',
  },
  toggleIcon: {
    position: 'absolute',
    padding: 5,
    borderRadius: 15,
    // borderWidth: 1,
    // backgroundColor: 'red',
    bottom: 0,
    zIndex: 999,
    right: 0,
  },
  wrapperDescription: {
    paddingVertical: 10,
    borderTopColor: 'lightgray',
    // backgroundColor: 'red',
    borderTopWidth: 1.5,
    borderStyle: 'dashed',
  },
  wrapperDoctorContainer: {
    padding: 10,
    flexDirection: 'row',
    backgroundColor: Colors.gray.gray95,
    borderRadius: 10,
  },
});

export default styles;
